### ISSUE TITLE
[BUG] - Speakers stop working after a few minutes

### ISSUE THREAD

**Issue by MarkPCExpertYT** [woa-vayu/POCOX3Pro-Guides#67]
### Description

The speakers stop working after a few minutes. The headphone audio is fine after the speakers stop.
Running Windows 11 build 23H2 on the phone, dualbooted with LineageOS 20.

### Reproduction steps

```bash
1. Boot Windows
2. Play audio (it works fine then)
3. Stop playing audio and do anything else for a bit
4. Try playing audio again (then it doesn't work)
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Phone.
- [X] There is no issue already describing my problem.

**Comment by remtrik** [comment]
Known, won't be fixed anytime soon
