### ISSUE TITLE
Internal Storage Not Found

### ISSUE THREAD

**Issue by Thoufeeq0000** [woa-vayu/POCOX3Pro-Guides#70]
### Question

I Installed Windows 11 On My Poco X3 Pro On August , Yesterday,I Am Going To Uninstall Windows 11 For Some Reasons,So I Type "adb shell restore",Then I Check Still Windows Partition Didn't Merge And Internal Storage Disappered
![IMG_20241224_142404](https://github.com/user-attachments/assets/3696c1d1-787d-4d0c-a756-528f3277a642)
![IMG_20241224_142425](https://github.com/user-attachments/assets/41b9de6b-334b-4e3b-a822-6d6d16eba9ff)
![IMG_20241224_142441](https://github.com/user-attachments/assets/a3c65a55-b677-42d6-afdd-741bf8ee2267)
Please Help Me🤧 And Watch The Images I Added
Please Reply😢

### Agreement

- [x] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
type `adb shell restore` again

This is caused by you having old partitions, which the recovery does not like

**Comment by Daniel224455** [comment]
kutas

**Comment by Thoufeeq0000** [comment]
> type `adb shell restore` again
> 
> This is caused by you having old partitions, which the recovery does not like

I didn't understand what you talk

**Comment by n00b69** [comment]
@Thoufeeq0000 Run adb shell restore again
